language: go
go:
  - 1.9.x

services:
  - postgresql
  - mysql

addons:
  postgresql: "9.4"

before_script:
  - mysql -e 'CREATE DATABASE prana;'
  - psql -c 'CREATE DATABASE prana;' -U postgres

install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
  - go install github.com/onsi/ginkgo/ginkgo
  - go install github.com/Masterminds/glide
  - export PATH=$PATH:$HOME/gopath/bin
  - glide install

script:
  - ginkgo -r -v -covermode=atomic

after_success:
  - cmd/cover.sh
  - bash <(curl -s https://codecov.io/bash)
